// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AwardsCom: typeof import('./src/components/ModelComs/AwardsCom.vue')['default']
    BaseInfoOptions: typeof import('./src/components/CommonOptions/BaseInfoOptions.vue')['default']
    CampusExperienceCom: typeof import('./src/components/ModelComs/CampusExperienceCom.vue')['default']
    CommonOptions: typeof import('./src/components/CommonOptions/CommonOptions.vue')['default']
    CommonTitleOptions: typeof import('./src/components/CommonOptions/CommonTitleOptions.vue')['default']
    EduBackgroundCom: typeof import('./src/components/ModelComs/EduBackgroundCom.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FooterCom: typeof import('./src/components/FooterCom/FooterCom.vue')['default']
    GlobalOptions: typeof import('./src/components/CommonOptions/GlobalOptions.vue')['default']
    HobbiesCom: typeof import('./src/components/ModelComs/HobbiesCom.vue')['default']
    ImportJsonDialog: typeof import('./src/components/ImportJsonDialog/ImportJsonDialog.vue')['default']
    InternshipExperienceCom: typeof import('./src/components/ModelComs/InternshipExperienceCom.vue')['default']
    JobIntentionCom: typeof import('./src/components/ModelComs/JobIntentionCom.vue')['default']
    LoadingCom: typeof import('./src/components/Loading/LoadingCom.vue')['default']
    ModelBox: typeof import('./src/components/ModelBox/ModelBox.vue')['default']
    NavBar: typeof import('./src/components/NavBar/NavBar.vue')['default']
    PreviewImage: typeof import('./src/components/PreviewImage/PreviewImage.vue')['default']
    ProjectExperienceCom: typeof import('./src/components/ModelComs/ProjectExperienceCom.vue')['default']
    ResumeTitleOptions: typeof import('./src/components/CommonOptions/ResumeTitleOptions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelfEvaluationCom: typeof import('./src/components/ModelComs/SelfEvaluationCom.vue')['default']
    SkillSpecialtiesCom: typeof import('./src/components/ModelComs/SkillSpecialtiesCom.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
    WorkExperienceCom: typeof import('./src/components/ModelComs/WorkExperienceCom.vue')['default']
    WorksDisplayCom: typeof import('./src/components/ModelComs/WorksDisplayCom.vue')['default']
  }
}
