// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AvatarPopoverShape: typeof import('./components/AvatarPopoverShape/AvatarPopoverShape.vue')['default'];
    AwardsCom: typeof import('./components/ModelComs/AwardsCom.vue')['default'];
    CampusExperienceCom: typeof import('./components/ModelComs/CampusExperienceCom.vue')['default'];
    ColorPickerCustom: typeof import('./components/ColorPicker/ColorPickerCustom.vue')['default'];
    CommEditor: typeof import('./components/CommEditor/CommEditor.vue')['default'];
    CommonLoading: typeof import('./components/CommonLoading/CommonLoading.vue')['default'];
    DateFormItem: typeof import('./components/DateFormItem/DateFormItem.vue')['default'];
    EduBackgroundCom: typeof import('./components/ModelComs/EduBackgroundCom.vue')['default'];
    ElAvatar: typeof import('element-plus/es')['ElAvatar'];
    ElBacktop: typeof import('element-plus/es')['ElBacktop'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
    ElDialog: typeof import('element-plus/es')['ElDialog'];
    ElDropdown: typeof import('element-plus/es')['ElDropdown'];
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElImage: typeof import('element-plus/es')['ElImage'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElOption: typeof import('element-plus/es')['ElOption'];
    ElPagination: typeof import('element-plus/es')['ElPagination'];
    ElPopover: typeof import('element-plus/es')['ElPopover'];
    ElSelect: typeof import('element-plus/es')['ElSelect'];
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton'];
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem'];
    ElSlider: typeof import('element-plus/es')['ElSlider'];
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
    ElTooltip: typeof import('element-plus/es')['ElTooltip'];
    ElUpload: typeof import('element-plus/es')['ElUpload'];
    FooterCom: typeof import('./components/FooterCom/FooterCom.vue')['default'];
    GithubCard: typeof import('./components/GihubCard/GithubCard.vue')['default'];
    HobbiesCom: typeof import('./components/ModelComs/HobbiesCom.vue')['default'];
    ImportJsonDialog: typeof import('./components/ImportJsonDialog/ImportJsonDialog.vue')['default'];
    InternshipExperienceCom: typeof import('./components/ModelComs/InternshipExperienceCom.vue')['default'];
    JobIntentionCom: typeof import('./components/ModelComs/JobIntentionCom.vue')['default'];
    LoadingCom: typeof import('./components/Loading/LoadingCom.vue')['default'];
    LoginDialog: typeof import('./components/LoginDialog/LoginDialog.vue')['default'];
    LogoCom: typeof import('./components/LogoCom/LogoCom.vue')['default'];
    ModelBox: typeof import('./components/ModelBox/ModelBox.vue')['default'];
    NavBar: typeof import('./components/NavBar/NavBar.vue')['default'];
    NoData: typeof import('./components/NoData/NoData.vue')['default'];
    Pagination: typeof import('./components/Pagination/pagination.vue')['default'];
    PreviewImage: typeof import('./components/PreviewImage/PreviewImage.vue')['default'];
    ProcessBarDialog: typeof import('./components/ProcessBarDialog/ProcessBarDialog.vue')['default'];
    ProjectExperienceCom: typeof import('./components/ModelComs/ProjectExperienceCom.vue')['default'];
    QrCode: typeof import('./components/QrCode/QrCode.vue')['default'];
    ResumeBackgroundPopover: typeof import('./components/ResumeBackgroundPopover/ResumeBackgroundPopover.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SelfEvaluationCom: typeof import('./components/ModelComs/SelfEvaluationCom.vue')['default'];
    SkeletonCard: typeof import('./components/SkeletonCard/SkeletonCard.vue')['default'];
    SkillSpecialtiesCom: typeof import('./components/ModelComs/SkillSpecialtiesCom.vue')['default'];
    SvgIcon: typeof import('./components/SvgIcon/SvgIcon.vue')['default'];
    TemplateCard: typeof import('./components/TemplateCard/TemplateCard.vue')['default'];
    TipJsonDialog: typeof import('./components/TipJsonDialog/TipJsonDialog.vue')['default'];
    WorkExperienceCom: typeof import('./components/ModelComs/WorkExperienceCom.vue')['default'];
    WorksDisplayCom: typeof import('./components/ModelComs/WorksDisplayCom.vue')['default'];
  }
}
