import IRESUMEJSON from '@/interface/resume';

const TEMPLATE_3_JSON: IRESUMEJSON = {
  ID: '',
  NAME: '',
  TITLE: '我的简历',
  LAYOUT: 'classical',
  COMPONENTS: [
    {
      keyId: '60d785cb-e4ed-4db3-aab6-d77c6c3739bb',
      model: 'RESUME_TITLE',
      cptName: 'RESUME_TITLE_1',
      cptOptionsName: 'RESUME_TITLE_OPTIONS',
      cptTitle: '简历标题',
      cptX: 0,
      cptY: 0,
      cptZ: 0,
      cptHeight: '100px',
      cptWidth: '100%',
      layout: '',
      show: false,
      style: {
        textColor: '#fff',
        textFontSize: '16px',
        textFontWeight: 600,
        backgroundColor: '#000',
        mBottom: '35px',
        mTop: '15px',
        themeColor: '#000',
        firstTitleFontSize: '20px',
        titleColor: '#121c26',
        titleFontSize: '30px',
        titleFontWeight: 500,
        pTopBottom: '0',
        pLeftRight: '0'
      },
      data: {}
    },
    {
      keyId: '20b6991e-8414-4b13-bbd2-288067ee61a8',
      model: 'BASE_INFO',
      cptName: 'BASE_INFO_1',
      cptOptionsName: 'BASE_INFO_OPTIONS',
      cptTitle: '基础资料',
      cptX: 0,
      cptY: 0,
      cptZ: 0,
      cptHeight: '100px',
      cptWidth: '100%',
      layout: '',
      show: true,
      style: {
        titleColor: '#fff',
        titleFontSize: '30px',
        textFontSize: '14px',
        titleFontWeight: 400,
        textFontWeight: 500,
        textColor: '#757575',
        mBottom: '40px',
        mTop: '0px',
        themeColor: '#000',
        firstTitleFontSize: '20px',
        pTopBottom: '0',
        pLeftRight: '40px'
      },
      data: {}
    },
    {
      keyId: 'dfb3f700-dab7-461b-93ac-08e6f5beca5b',
      model: 'JOB_INTENTION',
      cptName: 'JOB_INTENTION_1',
      cptOptionsName: 'JOB_INTENTION_OPTIONS',
      cptTitle: '求职意向',
      cptX: 0,
      cptY: 0,
      cptZ: 0,
      cptHeight: '100px',
      cptWidth: '100%',
      layout: '',
      show: true,
      style: {
        textColor: '#757575',
        textFontSize: '14px',
        textFontWeight: 500,
        mBottom: '30px',
        mTop: '0px',
        themeColor: '#000',
        firstTitleFontSize: '20px',
        titleColor: '#121c26',
        titleFontSize: '30px',
        titleFontWeight: 500,
        pTopBottom: '0',
        pLeftRight: '40px'
      },
      data: {}
    },
    {
      keyId: '771953b7-65dd-4ec3-b571-1a8683906ad9',
      model: 'EDU_BACKGROUND',
      cptName: 'EDU_BACKGROUND_1',
      cptOptionsName: 'EDU_BACKGROUND_OPTIONS',
      cptTitle: '教育背景',
      cptX: 0,
      cptY: 0,
      cptZ: 0,
      cptHeight: '50px',
      cptWidth: '100%',
      layout: '',
      show: true,
      style: {
        textColor: '#757575',
        textFontSize: '14px',
        textFontWeight: 500,
        titleColor: '#666666',
        titleFontSize: '14px',
        titleFontWeight: 600,
        mBottom: '30px',
        mTop: '0px',
        themeColor: '#000',
        firstTitleFontSize: '20px',
        pTopBottom: '0',
        pLeftRight: '40px'
      },
      data: {}
    },
    {
      keyId: 'dbcc9cbe-188e-4a49-a486-2ad4f23a030a',
      model: 'SKILL_SPECIALTIES',
      cptName: 'SKILL_SPECIALTIES_1',
      cptOptionsName: 'SKILL_SPECIALTIES_OPTIONS',
      cptTitle: '技能特长',
      cptX: 0,
      cptY: 0,
      cptZ: 0,
      cptHeight: '50px',
      cptWidth: '100%',
      layout: '',
      show: true,
      style: {
        textColor: '#757575',
        textFontSize: '14px',
        textFontWeight: 500,
        mBottom: '30px',
        mTop: '0px',
        themeColor: '#000',
        firstTitleFontSize: '20px',
        titleColor: '#666666',
        titleFontSize: '14px',
        titleFontWeight: 600,
        backgroundColor: '#000',
        pTopBottom: '0',
        pLeftRight: '40px'
      },
      data: {}
    },
    {
      keyId: '8399cdc7-c624-4858-aafc-5cff711e6646',
      model: 'CAMPUS_EXPERIENCE',
      cptName: 'CAMPUS_EXPERIENCE_1',
      cptOptionsName: 'CAMPUS_EXPERIENCE_OPTIONS',
      cptTitle: '校园经历',
      cptX: 0,
      cptY: 0,
      cptZ: 0,
      cptHeight: '50px',
      cptWidth: '100%',
      layout: '',
      show: true,
      style: {
        titleColor: '#666',
        titleFontSize: '14px',
        titleFontWeight: 600,
        textColor: '#757575',
        textFontSize: '14px',
        textFontWeight: 500,
        mBottom: '30px',
        mTop: '0px',
        themeColor: '#000',
        firstTitleFontSize: '20px',
        backgroundColor: '#000',
        pTopBottom: '0',
        pLeftRight: '40px'
      },
      data: {}
    },
    {
      keyId: '6c6ff9b8-1c4d-4bd9-a43a-bc912ed1692b',
      model: 'INTERNSHIP_EXPERIENCE',
      cptName: 'INTERNSHIP_EXPERIENCE_1',
      cptOptionsName: 'INTERNSHIP_EXPERIENCE_OPTIONS',
      cptTitle: '实习经验',
      cptX: 0,
      cptY: 0,
      cptZ: 0,
      cptHeight: '50px',
      cptWidth: '100%',
      layout: '',
      show: true,
      style: {
        titleColor: '#666',
        titleFontSize: '14px',
        titleFontWeight: 600,
        textColor: '#757575',
        textFontSize: '14px',
        textFontWeight: 500,
        mBottom: '30px',
        mTop: '0px',
        themeColor: '#000',
        firstTitleFontSize: '20px',
        backgroundColor: '#000',
        pTopBottom: '0',
        pLeftRight: '40px'
      },
      data: {}
    },
    {
      keyId: '940a00f9-925b-4451-9b9c-3678b3b6005c',
      model: 'WORK_EXPERIENCE',
      cptName: 'WORK_EXPERIENCE_1',
      cptOptionsName: 'WORK_EXPERIENCE_OPTIONS',
      cptTitle: '工作经验',
      cptX: 0,
      cptY: 0,
      cptZ: 0,
      cptHeight: '50px',
      cptWidth: '100%',
      layout: '',
      show: true,
      style: {
        titleColor: '#666',
        titleFontSize: '14px',
        titleFontWeight: 600,
        textColor: '#757575',
        textFontSize: '14px',
        textFontWeight: 500,
        mBottom: '30px',
        mTop: '0px',
        themeColor: '#000',
        firstTitleFontSize: '20px',
        backgroundColor: '#000',
        pTopBottom: '0',
        pLeftRight: '40px'
      },
      data: {}
    },
    {
      keyId: '3486820a-6287-4eac-8035-e9aa0d4c4b8c',
      model: 'PROJECT_EXPERIENCE',
      cptName: 'PROJECT_EXPERIENCE_1',
      cptOptionsName: 'PROJECT_EXPERIENCE_OPTIONS',
      cptTitle: '项目经验',
      cptX: 0,
      cptY: 0,
      cptZ: 0,
      cptHeight: '50px',
      cptWidth: '100%',
      layout: '',
      show: true,
      style: {
        titleColor: '#666',
        titleFontSize: '14px',
        titleFontWeight: 600,
        textColor: '#757575',
        textFontSize: '14px',
        textFontWeight: 500,
        mBottom: '30px',
        mTop: '0px',
        themeColor: '#000',
        firstTitleFontSize: '20px',
        backgroundColor: '#000',
        pTopBottom: '0',
        pLeftRight: '40px'
      },
      data: {}
    },
    {
      keyId: '97bfd4ac-f141-49b1-96de-b15272ea9f07',
      model: 'AWARDS',
      cptName: 'AWARDS_1',
      cptOptionsName: 'AWARDS_OPTIONS',
      cptTitle: '荣誉奖项',
      cptX: 0,
      cptY: 0,
      cptZ: 0,
      cptHeight: '50px',
      cptWidth: '100%',
      layout: '',
      show: true,
      style: {
        textColor: '#757575',
        textFontSize: '14px',
        textFontWeight: 500,
        titleColor: '#666666',
        titleFontSize: '14px',
        titleFontWeight: 600,
        mBottom: '30px',
        mTop: '0px',
        themeColor: '#000',
        firstTitleFontSize: '20px',
        backgroundColor: '#000',
        pTopBottom: '0',
        pLeftRight: '40px'
      },
      data: {}
    },
    {
      keyId: '0ae03905-f823-4667-83cb-9ff79d6b608d',
      model: 'HOBBIES',
      cptName: 'HOBBIES_1',
      cptOptionsName: 'HOBBIES_OPTIONS',
      cptTitle: '兴趣爱好',
      cptX: 0,
      cptY: 0,
      cptZ: 0,
      cptHeight: '50px',
      cptWidth: '100%',
      layout: '',
      show: true,
      style: {
        themeColor: '#000',
        firstTitleFontSize: '20px',
        textColor: '#757575',
        textFontSize: '14px',
        textFontWeight: 500,
        titleColor: '#666666',
        titleFontSize: '14px',
        titleFontWeight: 600,
        backgroundColor: '#000',
        mBottom: '35px',
        mTop: '0px',
        pTopBottom: '0',
        pLeftRight: '40px'
      },
      data: {}
    },
    {
      keyId: '987bfb09-31e7-4a67-9305-d1138bc6bef2',
      model: 'SELF_EVALUATION',
      cptName: 'SELF_EVALUATION_1',
      cptOptionsName: 'SELF_EVALUATION_OPTIONS',
      cptTitle: '自我评价',
      cptX: 0,
      cptY: 0,
      cptZ: 0,
      cptHeight: '50px',
      cptWidth: '100%',
      layout: '',
      show: true,
      style: {
        textColor: '#757575',
        textFontSize: '14px',
        textFontWeight: 500,
        mBottom: '30px',
        mTop: '0px',
        themeColor: '#000',
        firstTitleFontSize: '20px',
        titleColor: '#666666',
        titleFontSize: '14px',
        titleFontWeight: 600,
        backgroundColor: '#000',
        pTopBottom: '0',
        pLeftRight: '40px'
      },
      data: {}
    },
    {
      keyId: 'e669991a-e2cc-4557-bcf1-14000624ccf5',
      model: 'WORKS_DISPLAY',
      cptName: 'WORKS_DISPLAY_1',
      cptOptionsName: 'WORKS_DISPLAY_OPTIONS',
      cptTitle: '作评展示',
      cptX: 0,
      cptY: 0,
      cptZ: 0,
      cptHeight: '50px',
      cptWidth: '100%',
      layout: '',
      show: true,
      style: {
        textColor: '#757575',
        textFontSize: '14px',
        textFontWeight: 500,
        mBottom: '30px',
        mTop: '0px',
        themeColor: '#000',
        firstTitleFontSize: '20px',
        titleColor: '#666666',
        titleFontSize: '14px',
        titleFontWeight: 600,
        backgroundColor: '#000',
        pTopBottom: '0',
        pLeftRight: '40px'
      },
      data: {}
    }
  ],
  GLOBAL_STYLE: {
    themeColor: '#079cfa', // 主题色
    firstTitleFontSize: '20px', // 一级标题
    secondTitleFontSize: '14px', // 二级标题
    textFontSize: '14px', // 正文
    secondTitleColor: '#666', // 二级标题字体颜色
    textFontColor: '#757575', // 正文字体颜色
    secondTitleWeight: 600, // 二级标题字体粗细
    textFontWeight: 500, // 正文字体粗细
    modelMarginTop: '0px',
    modelMarginBottom: '45px',
    pTopBottom: '0',
    pLeftRight: '40px',
    leftWidth: '',
    rightWidth: '',
    leftThemeColor: '',
    rightThemeColor: ''
  }
};
export default TEMPLATE_3_JSON;
